server:
  port: 8080
  error:    path: /error
  servlet:    session:      timeout: 30m
  tomcat:    basedir: ./tomcat
    accesslog:      buffered: true
      directory:  ./logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      prefix: access_log
      rename-on-rotate: false
      pattern: common
      request-attributes-enabled: false
      rotate: true
      max-days: 60
    max-threads: 500
    uri-encoding: utf-8
spring:  servlet:    multipart:      enabled: true
      file-size-threshold: 0
      max-file-size: 1MB
      max-request-size: 10MB
      resolve-lazily: false
  http:    encoding:      enabled: true
      charset: utf-8
      force: true
logging:  config: classpath:log4j2.xml
proj:
  name: "@project.name@"
  description: "@project.description@"
  version: "@project.version@"
swagger: 
  enable: true 
#  title: MDD Boot Demo
#  version: "@project.version@"
#  description: MDD Boot Demo
datasource:
  default:
    url: jdbc:sqlserver://192.168.5.1:2004;DatabaseName=master
    username: sa
    password: 
  first:
    url: jdbc:sqlserver://192.168.10.155:1433;DatabaseName=Z9公司_cs
    username: sa
    password: 
  second:
    url: jdbc:sqlserver://192.168.5.1:2004;DatabaseName=sqlTest
    username: sa
    password: 